name: Test CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  leximon-homework-required:
    runs-on: ubuntu-latest
    if: always()
    needs: [lint]
    steps:
      - name: Check results
        run: echo "all good, merge welll"
