name: Test CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  leximon-homework-required:
    runs-on: ubuntu-latest
    if: always()
    needs: [lint]
    steps:
      - name: Check results
        run: |
          echo '${{ toJSON(needs) }}' | jq -e '
            to_entries |
            map(select(.value.result != "success" and .value.result != "skipped")) |
            if length > 0 then
              .[0] | "Failed: " + .key + " (" + .value.result + ")" | halt_error(1)
            else
              "All jobs passed or were skipped"
            end
          '
